### ISSUE TITLE
Moving to Nuxt Community

### ISSUE THREAD

**Issue by Atinux** [yuki-torii/awesome-nuxt#1]
Hi @limichange 

Would you be ok to move `awesome-nuxt`  into https://github.com/nuxt-community?

This will add more visibiilty and you will also be an admin of the repository :)

**Comment by Atinux** [comment]
If you agree, could you put me as an admin of this repo so I can move it to `nuxt-community`?

**Comment by limichange** [comment]
https://github.com/yuki-torii/awesome-nuxt/invitations

👌
